site_name: Splashtop Syslog Guide
site_url: https://my-syslog-docs.readthedocs.io  # 部署后换成你的域名

theme:
  name: material
  language: en
  logo: assets/Splashtop-Logo_main 1.png
  favicon: assets/Logo_main1.png
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  features:
    - navigation.instant
    - navigation.expand
    - content.code.annotate

nav:
  - Syslog:
      - Overview: syslog-events.md
      - Syslog Format: events/syslog-format.md
      - Events and Fields:
          - d1Auth: events/Syslog events and fields.md
          - d2Management: events/Syslog events and fields.md
          - d3Settings: events/Syslog events and fields.md
          - d4Endpoints: events/Syslog events and fields.md
          - d5Service Desk: events/Syslog events and fields.md
          - d6Log: events/Syslog events and fields.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/little-potato/my-syslog-docs
