site_name: Syslog Events Documentation
site_url: https://my-syslog-docs.readthedocs.io  # 部署后换成你的域名

theme:
  name: material
  language: en
  logo: assets/Splashtop=Logo_main 1.png
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - toc.integrate
    - content.code.annotate
    - content.action.edit

nav:
  - 首页: index.md
  - Syslog 事件:
      - 总览: syslog-events.md
      - 认证事件: events/authentication.md
      - 授权事件: events/authorization.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/little-potato/my-syslog-docs
